<a href="https://colab.research.google.com/github/agmarrugo/computer-vision-utb/blob/main/notebooks/00_Linear_algebra_with_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Linear algebra with Numpy

Andrés Marrugo, PhD    
Universidad Tecnológica de Bolívar

Based on the jupyter notebook by [Vince Knight](https://github.com/drvinceknight/Python-Mathematics-Handbook)

Many computer vision algorithms require numeric computations performed with matrices and these are best solved with [Numpy](http://www.numpy.org/) a high performance numerical computing library.

Here is how it is described: 

> NumPy is the fundamental package for scientific computing with Python. It contains among other things: [...]
 useful linear algebra, Fourier transform, and random number capabilities.

This notebook is a way to review several linear algebra concepts and to get acquainted with their computation in Python. In this section we will see how to:

- Manipulate matrices;
- Solve Matrix equations;
- Calculate Matrix inverse and determinants.

## Manipulating matrices

It is straightforward to create a Matrix using Numpy. Let us consider the following as a examples:

$$
A = \begin{pmatrix}
5 & 6 & 2\\
4 & 7 & 19\\
0 & 3 & 12
\end{pmatrix}
$$

$$
B = \begin{pmatrix}
14 & -2 & 12\\
4 & 4 & 5\\
5 & 5 & 1
\end{pmatrix}
$$


First, we need to import Numpy:

In [ ]:
import numpy as np

Now we can define $A$:

In [ ]:
A = np.matrix([[5, 6, 2],
               [4, 7, 19],
               [0, 3, 12]])

In [ ]:
A

matrix([[ 5,  6,  2],
        [ 4,  7, 19],
        [ 0,  3, 12]])

In [ ]:
B = np.matrix([[14, -2, 12],
               [4, 4, 5],
               [5, 5, 1]])

In [ ]:
B

matrix([[14, -2, 12],
        [ 4,  4,  5],
        [ 5,  5,  1]])

We can obtain the following straightforwardly:

- $5A$ (or any other scalar multiple of $A$);
- $A ^ 3$ (or any other exponent of $A$);
- $A + B$;
- $A - B$;
- $AB$

In [ ]:
5 * A

matrix([[25, 30, 10],
        [20, 35, 95],
        [ 0, 15, 60]])

In [ ]:
A ** 3

matrix([[ 557, 1284, 3356],
        [ 760, 2305, 6994],
        [ 288, 1074, 3519]])

In [ ]:
A + B

matrix([[19,  4, 14],
        [ 8, 11, 24],
        [ 5,  8, 13]])

In [ ]:
A - B

matrix([[ -9,   8, -10],
        [  0,   3,  14],
        [ -5,  -2,  11]])

In [ ]:
A * B

matrix([[104,  24,  92],
        [179, 115, 102],
        [ 72,  72,  27]])

**Matrix multiplication.** Unfortunately, there are many ways to do [matrix multiplication in Python](https://blog.finxter.com/numpy-matmul-operator/ "NumPy Matrix Multiplication — np.matmul() and @ [Ultimate Guide] | Finxter"). The suggested way is to used the `@` operator because the `*` does not perform matrix multiplication unless the numpy.matrix subclass is used.

Check that `A @ B` produces the same result.

In [ ]:
A @ B

matrix([[104,  24,  92],
        [179, 115, 102],
        [ 72,  72,  27]])

---

**EXERCISE** Compute $A ^ 2 - 2 A + 3$ with:

$$A = 
\begin{pmatrix}
1 & -1\\
2 & 1
\end{pmatrix}
$$

---

In [ ]:
# Write here the solution

## Solving Matrix equations

We can use Numpy to (efficiently) solve large systems of equations of the form:

$$Ax=b$$

Let us illustrate that with:

$$
A = \begin{pmatrix}
5 & 6 & 2\\
4 & 7 & 19\\
0 & 3 & 12
\end{pmatrix}
$$

$$
b = \begin{pmatrix}
-1\\
2\\
1 
\end{pmatrix}
$$

In [ ]:
A = np.matrix([[5, 6, 2],
               [4, 7, 19],
               [0, 3, 12]])
b = np.matrix([[-1], [2], [1]])

We use the `linalg.solve` command:

In [ ]:
x = np.linalg.solve(A, b)
x

matrix([[ 0.45736434],
        [-0.62790698],
        [ 0.24031008]])

We can verify our result:

In [ ]:
A * x

matrix([[-1.],
        [ 2.],
        [ 1.]])

---

**EXERCISE** Compute the solutions to the matrix equation $Bx=b$ (using the $B$ defined earlier).

---

In [ ]:
# Write the solution here

## Matrix inversion and determinants

Computing the inverse of a matrix is straightforward:

In [ ]:
Ainv = np.linalg.inv(A)
Ainv

matrix([[-0.20930233,  0.51162791, -0.7751938 ],
        [ 0.37209302, -0.46511628,  0.6744186 ],
        [-0.09302326,  0.11627907, -0.08527132]])

We can verify that $A^{-1}A=\mathbb{1}$:

In [ ]:
A * Ainv

matrix([[ 1.00000000e+00,  4.99600361e-16, -2.77555756e-17],
        [ 1.38777878e-16,  1.00000000e+00,  1.80411242e-16],
        [ 1.11022302e-16,  1.11022302e-16,  1.00000000e+00]])

The above might not look like the identity matrix but if you look closer you see that the diagonals are all `1` and the off diagonals are a **very** small number (which from a computer's point of view is `0`).

To calculate the determinant:

In [ ]:
np.linalg.det(A)

-129.00000000000009

---

**EXERCISE** Compute the inverse and determinant of $B$ (defined previously).

---

In [ ]:
# Write the solution here

## Summary

In this section we have seen how to using Numpy:

- Manipulate matrices;
- Solve linear systems;
- Compute Matrix inverses and determinants.

This again just touches on the capabilities of Numpy. For more information please refere to this [Python tutorial.](https://github.com/kuleshov/teaching-material/blob/master/tutorials/python/cs228-python-tutorial.ipynb)